//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Dormitory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager_Info
    {
        public int ID { get; set; }
        public int ManagerID { get; set; }
        public int RoomID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
