//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Dormitory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int ID { get; set; }
        public string ManagerName { get; set; }
        public string PhoneNumber { get; set; }
        public string BuildingID { get; set; }
        public string Gmail { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Username { get; set; }
    }
}
