//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Dormitory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string Username { get; set; }
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public string Class { get; set; }
        public string Major { get; set; }
        public string AcademicYear { get; set; }
        public string PersonalID { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string PlaceOfIssue { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string PhoneNumber { get; set; }
        public string Gmail { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Commune { get; set; }
    }
}
