//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Dormitory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInRoom
    {
        public int BuildingId { get; set; }
        public string RoomName { get; set; }
        public int RoomID { get; set; }
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public string Class { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
